// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Jy-Nob_TzJMnL1WqMLuZ-45xM7en-hY',
    appId: '1:244814410688:web:af45a54670df6b6332ce25',
    messagingSenderId: '244814410688',
    projectId: 'controle-abastecimento-ca741',
    authDomain: 'controle-abastecimento-ca741.firebaseapp.com',
    storageBucket: 'controle-abastecimento-ca741.firebasestorage.app',
    measurementId: 'G-TM8W7V3HJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3C_oKFC5FV_QVYXFEj1sMubvQB8aAqmY',
    appId: '1:244814410688:android:5c258f618ecb6b5632ce25',
    messagingSenderId: '244814410688',
    projectId: 'controle-abastecimento-ca741',
    storageBucket: 'controle-abastecimento-ca741.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY6GV_XTveqsN0xzAl3GLnZI66qoCNCo8',
    appId: '1:244814410688:ios:4895ec6314f89a5032ce25',
    messagingSenderId: '244814410688',
    projectId: 'controle-abastecimento-ca741',
    storageBucket: 'controle-abastecimento-ca741.firebasestorage.app',
    iosBundleId: 'com.example.controleAbastecimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY6GV_XTveqsN0xzAl3GLnZI66qoCNCo8',
    appId: '1:244814410688:ios:4895ec6314f89a5032ce25',
    messagingSenderId: '244814410688',
    projectId: 'controle-abastecimento-ca741',
    storageBucket: 'controle-abastecimento-ca741.firebasestorage.app',
    iosBundleId: 'com.example.controleAbastecimento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7Jy-Nob_TzJMnL1WqMLuZ-45xM7en-hY',
    appId: '1:244814410688:web:bc639b50d64ffb2332ce25',
    messagingSenderId: '244814410688',
    projectId: 'controle-abastecimento-ca741',
    authDomain: 'controle-abastecimento-ca741.firebaseapp.com',
    storageBucket: 'controle-abastecimento-ca741.firebasestorage.app',
    measurementId: 'G-R0F66NDCPP',
  );

}